### ISSUE TITLE
predictable_random_int() should include script name

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/module-standardiser#20]
`predictable_random_int()` currently randomises based on `$MODULE_DIR` - it should also be random based on the script that calls it.  Could use debug_backtrace() to get the script name that called it.  This allows the random ints to be random between scripts within a module

Not that updating this will update all cron times, so it would require a mass update

~~Do at same time as https://github.com/silverstripe/module-standardiser/issues/21~~

## PR
- https://github.com/silverstripe/module-standardiser/pull/39

**Comment by GuySartorelli** [comment]
PR merged
