### ISSUE TITLE
Repository owner is incorrectly identified for the simple theme

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/module-standardiser#44]
In https://github.com/silverstripe/silverstripe-simple/blob/3/.github/workflows/merge-up.yml we see this:
`github.repository_owner == 'silverstripe-themes'`
Should be `github.repository_owner == 'silverstripe'`

This is causing the merge-ups to not run for that repository. It's theoretically possible other repos are similarly incorrect.

**Comment by emteknetnz** [comment]
This will probably be resolved by https://github.com/silverstripe/module-standardiser/pull/45

**Comment by GuySartorelli** [comment]
This was fixed
